<a href="https://colab.research.google.com/github/Sreegoth/git_python/blob/main/preprocessor_temp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# reading data
import pandas as pd
data=pd.read_csv("salary_note.csv")

In [ ]:
data


YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
data.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [ ]:
data['YearsExperience']

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [ ]:
data.head(3)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0

In [ ]:
# step -2 separete tghe both input and output
X=data.iloc[:,0].values
X=X.reshape(-1,1)

In [ ]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
Y=data.iloc[:,1].values


In [ ]:
Y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [ ]:
print(Y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


In [ ]:
# step -3 
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
X_train

array([[ 3.9],
       [ 1.1],
       [ 3.7],
       [ 8.2],
       [ 9. ],
       [ 3.2],
       [ 4.5],
       [ 6. ],
       [ 2.2],
       [10.5],
       [ 4. ],
       [ 2.9],
       [ 5.3],
       [ 1.3],
       [ 4.9],
       [ 9.6],
       [ 7.1],
       [ 3.2],
       [ 8.7],
       [ 4. ],
       [ 9.5],
       [ 3. ],
       [10.3],
       [ 1.5]])

In [ ]:
X_test

array([[5.9],
       [7.9],
       [4.1],
       [6.8],
       [5.1],
       [2. ]])

In [ ]:
Y_train

array([ 63218.,  39343.,  57189., 113812., 105582.,  64445.,  61111.,
        93940.,  39891., 121872.,  55794.,  56642.,  83088.,  46205.,
        67938., 112635.,  98273.,  54445., 109431.,  56957., 116969.,
        60150., 122391.,  37731.])

In [ ]:
Y_test

array([ 81363., 101302.,  57081.,  91738.,  66029.,  43525.])

In [ ]:
# Y=f(X)=aX+b
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
regressor.coef_

array([9358.98888959])

In [ ]:
regressor.intercept_

26868.542403688778

In [ ]:
regressor.predict

<bound method LinearModel.predict of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)>

In [ ]:
regressor.predict([[6]])

array([83022.47574122])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
regressor.predict(X_test)

array([ 82086.57685226, 100804.55463144,  65240.396851  ,  90509.66685289,
        74599.38574059,  45586.52018287])

In [ ]:
Y_test

array([ 81363., 101302.,  57081.,  91738.,  66029.,  43525.])